---
title: "Statistik och dataanalys III, 15 hp "
subtitle: "Inlämningsuppgift 1, 1.5 hp"
author: 
- Namn 1
- Namn 2
- Namn 3
date: last-modified
format: 
  html:
    self-contained: true
    code-line-numbers: true
  pdf: default  
  docx: default
toc: true
language: 
  title-block-author-single: " "
toc-title-document: "Innehåll"
crossref-fig-title: "Figur"
theme: Superhero
title-block-banner-color: Primary
title-block-published: "Publicerad"
author-title: "Gruppmedlemmar"
title-block-banner: true
editor: visual
---

```{r}
#| output: false
#| echo: false
# Denna chunk ska innehålla alla paket ni använder
library(remotes)
library(SUdatasets)
library(plotly)
library(mvtnorm)
library(tidyverse)
library(reshape2)
```

# Uppgift 1.1

För varje deluppgift gäller

-   Välmotiverade, korrekta svar
-   Tolkning/beskrivning av resultat
-   Eventuella figurer ska ha titlar och informativa axlar

```{r}
# Read df
df<-read.delim("doctorvisits.txt",sep =" ")
```

```{r}

hist(df$numvisit, col = "brown", breaks= 10)
hist(df$age, col = "pink", breaks= 30)


maxlength_educ <- round(max(df$educ))
hist(df$educ, col = "brown", breaks= maxlength_educ)
hist(df$loginc, col = "pink", breaks= 30)
```

# Heatmap

```{r}
# Correlation matrix
corr_matrix <- cor(df[sapply(df, is.numeric)])
# tidyplot needs long format use melt()
corr_matrix <- melt(corr_matrix)

ggplot(corr_matrix, aes(x = Var1, y= Var2, fill=value)) + 
  geom_tile() + scale_fill_gradient2(
    low = "white",      
    mid = "brown",      
    high = "red",      
    midpoint = 0.5,       
    name = "Correlation"
  ) +
  ggtitle("Correlation matrix") +
  labs(x= NULL, y = NULL)
```

# Uppgift 1.2

# Uppgift 1.3

# Uppgift 1.4

# Uppgift 1.5

# Uppgift 1.6

# Uppgift 1.7

# Uppgift 1.8
